export const REGION_OPTIONS_MAP = {
  DOLNOSLONSKIE: 'dolnośląskie',
  KUJAWSKO_POMORSKIE: 'kujawsko-pomorskie',
  LUBELSKIE: 'lubelskie',
  LUBUSKIE: 'lubuskie',
  LODZKIE: 'łódzkie',
  MALOPOLSKIE: 'małopolskie',
  MAZOWIECKIE: 'mazowieckie',
  OPOLSKIE: 'opolskie',
  PODKARPACKIE: 'podkarpackie',
  PODLASKIE: 'podlaskie',
  POMORSKIE: 'pomorskie',
  SLASKIE: 'śląskie',
  SWIETOKRZYSKIE: 'świętokrzyskie',
  WARMINSKO_MAZURSKIE: 'warmińsko-mazurskie',
  WIELKOPOLSKIE: 'wielkopolskie',
  ZACHODNIOPOMORSKIE: 'zachodniopomorskie',
} as const;
